# Generated by Django 4.1.5 on 2024-07-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalsBottom',
            fields=[
                ('timestamps', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Time')),
                ('data_1ch', models.FloatField(blank=True, default=0, verbose_name='data_1ch')),
                ('data_2ch', models.FloatField(blank=True, default=0, verbose_name='data_2ch')),
                ('data_3ch', models.FloatField(blank=True, default=0, verbose_name='data_3ch')),
                ('data_4ch', models.FloatField(blank=True, default=0, verbose_name='data_4ch')),
                ('data_5ch', models.FloatField(blank=True, default=0, verbose_name='data_5ch')),
                ('data_6ch', models.FloatField(blank=True, default=0, verbose_name='data_6ch')),
                ('data_7ch', models.FloatField(blank=True, default=0, verbose_name='data_6ch')),
                ('data_8ch', models.FloatField(blank=True, default=0, verbose_name='data_6ch')),
            ],
            options={
                'db_table': 'SignalsBottom',
            },
        ),
        migrations.CreateModel(
            name='SignalsSettings',
            fields=[
                ('par_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Name')),
                ('par_permission', models.CharField(default='RO', max_length=20, verbose_name='Permission')),
                ('par_value', models.FloatField(blank=True, default=0, verbose_name='Value')),
            ],
            options={
                'db_table': 'SignalsSettings',
            },
        ),
        migrations.CreateModel(
            name='SignalsTop',
            fields=[
                ('timestamps', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Time')),
                ('data_1ch', models.FloatField(blank=True, default=0, verbose_name='data_1ch')),
                ('data_2ch', models.FloatField(blank=True, default=0, verbose_name='data_2ch')),
                ('data_3ch', models.FloatField(blank=True, default=0, verbose_name='data_3ch')),
                ('data_4ch', models.FloatField(blank=True, default=0, verbose_name='data_4ch')),
                ('data_5ch', models.FloatField(blank=True, default=0, verbose_name='data_5ch')),
                ('data_6ch', models.FloatField(blank=True, default=0, verbose_name='data_6ch')),
                ('data_7ch', models.FloatField(blank=True, default=0, verbose_name='data_6ch')),
                ('data_8ch', models.FloatField(blank=True, default=0, verbose_name='data_6ch')),
            ],
            options={
                'db_table': 'SignalsTop',
            },
        ),
    ]
