# Generated by Django 4.1.5 on 2024-07-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalsbottom',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='signalstop',
            options={'managed': False},
        ),
    ]
