# Generated by Django 4.1.5 on 2024-07-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_signalsbottom_options_alter_signalstop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalsbottom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='signalstop',
            options={},
        ),
    ]
