# Generated by Django 4.1.5 on 2024-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_signalsbottom_options_alter_signalstop_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalsbottom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='signalstop',
            name='id',
        ),
        migrations.AlterField(
            model_name='signalsbottom',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='signalstop',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Time'),
        ),
    ]
